// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, BackboneFilteredCollection, oldFilter, socket, uniqueNumber, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  socket = $.atmosphere;

  Backbone = this.Backbone;

  _ = this._;

  oldFilter = Backbone.Collection.prototype.filter;

  uniqueNumber = function() {
    if (this.lastNumber != null) {
      this.lastNumber++;
    } else {
      this.lastNumber = 1;
    }
    return "BackboneFilteredCollection" + this.lastNumber;
  };

  BackboneFilteredCollection = (function(_super) {

    __extends(BackboneFilteredCollection, _super);

    function BackboneFilteredCollection(sourceCollection, filter) {
      this.sourceCollection = sourceCollection;
      this.filter = filter;
      BackboneFilteredCollection.__super__.constructor.call(this);
    }

    BackboneFilteredCollection.prototype.fetch = function() {
      return console.log("no fetch, should delegate");
    };

    return BackboneFilteredCollection;

  })(Backbone.Collection);

  Backbone.Collection.prototype.filter = function(filter) {
    var addAllMatching, addFilteredCollectionSupport, addListener, filteredCollection, handleAdd, handleChange, handleRemove;
    handleChange = function(model) {
      var addedTo, filteredCollection, removedFrom;
      removedFrom = (function() {
        var _i, _len, _ref, _results;
        _ref = this.filteredCollections;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          filteredCollection = _ref[_i];
          if (_.contains(filteredCollection.models, model) && !(filteredCollection.filter(model))) {
            _results.push(filteredCollection.remove(model));
          }
        }
        return _results;
      }).call(this);
      addedTo = (function() {
        var _i, _len, _ref, _results;
        _ref = this.filteredCollections;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          filteredCollection = _ref[_i];
          if (filteredCollection.filter(model)) {
            _results.push(filteredCollection.add(model));
          }
        }
        return _results;
      }).call(this);
      if ((addedTo.length === 1) && (removedFrom.length === 1)) {
        return addedTo.trigger("movedTo", removedFrom[0]);
      }
    };
    addAllMatching = function(models) {
      var model, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = models.length; _i < _len; _i++) {
        model = models[_i];
        _results.push(handleAdd(model));
      }
      return _results;
    };
    addListener = function(model) {
      var _this = this;
      return model.on("change", (function() {
        return handleChange.call(_this, model);
      }), "BackboneCollectionFiltering" + uniqueNumber());
    };
    handleAdd = function(model) {
      var filteredCollecton, _i, _len, _ref, _results;
      addListener.call(this, model);
      _ref = this.filteredCollections;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        filteredCollecton = _ref[_i];
        if (filteredCollection.filter(model)) {
          _results.push(filteredCollection.add(model));
        }
      }
      return _results;
    };
    handleRemove = function(model) {
      var filteredCollection, _i, _len, _ref, _results;
      _ref = this.filteredCollections;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        filteredCollection = _ref[_i];
        if (_.contains(filteredCollection.models, model)) {
          _results.push(filteredCollection.remove(model));
        }
      }
      return _results;
    };
    addFilteredCollectionSupport = function() {
      var _this = this;
      this.hasFilteredCollectionSupport = true;
      this.filteredCollections = [];
      this.on("add", (function(model) {
        return handleAdd.call(_this, model);
      }), "FilteredCollectionContext");
      this.on("remove", (function(model) {
        return handleRemove.call(_this, model);
      }), "FilteredCollectionContext");
      return this.on("reset", (function() {
        return addAllMatching.call(_this, _this.models);
      }), "FilteredCollectionContext");
    };
    if (!this.hasFilteredCollectionSupport) {
      addFilteredCollectionSupport.call(this);
    }
    filteredCollection = new BackboneFilteredCollection(this, filter);
    this.filteredCollections.push(filteredCollection);
    addAllMatching.call(filteredCollection, this.models);
    return filteredCollection;
  };

}).call(this);
